device_info:
  device:
    name: fanuc_robot
  manufacturer:
    name: FANUC
    uuid: ee260e78-d731-415a-84ca-4b02c487410c
  model:
    name: FANUC_m900ia_260l
    uuid: 9ad3c0ee-ec5e-4057-a297-d340e1484f01
  user_description: FANUC Robot
  serial_number: 123456789
  device_classes:
    - class_identifier:
        name: robot
        uuid: 39b513e7-21b9-4b49-8654-7537473030eb
      subclasses: 
        - serial
        - serial_six_axis        
  implemented_types:
    - com.robotraconteur.robotics.robot.Robot
robot_type: serial
robot_capabilities:
- jog_command
- trajectory_command
- position_command
chains:
- H:
  - x: 0.0
    y: 0.0
    z: 1.0
  - x: 0.0
    y: 1.0
    z: 0.0
  - x: 0.0
    y: -1.0
    z: 0.0
  - x: -1.0
    y: 0.0
    z: 0.0
  - x: 0.0
    y: -1.0
    z: 0.0
  - x: -1.0
    y: 0.0
    z: 0.0
  P:
  - x: 0.0
    y: 0.0
    z: 0.95
  - x: 0.37
    y: 0.0
    z: 0.0
  - x: 0.0
    y: 0.0
    z: 1.05
  - x: 0.0
    y: 0.0
    z: 0.2
  - x: 1.705
    y: 0.0
    z: 0.0
  - x: 0.27
    y: 0.0
    z: 0.0
  - x: 0.0
    y: 0.0
    z: 0.0
  flange_identifier: tool0
  flange_pose:
    orientation:
      w: 4.329780281177467e-17
      x: 0.7071067811865476
      y: -4.3297802811774664e-17
      z: 0.7071067811865475
    position:
      x: 0.0
      y: 0.0
      z: 0.0
  joint_numbers:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  link_identifiers:
  - base_link
  - link_1
  - link_2
  - link_3
  - link_4
  - link_5
  - link_6
  kin_chain_identifier: robot_arm
joint_info:
- default_effort_units: newton_meter
  default_units: radian
  joint_identifier: joint_1
  joint_limits:
    effort: 0.0
    lower: -3.141593
    upper: 3.141593
    velocity: 1.745329
    acceleration: 3.15
  joint_type: revolute
  passive: false
- default_effort_units: newton_meter
  default_units: radian
  joint_identifier: joint_2
  joint_limits:
    effort: 0.0
    lower: -1.308997
    upper: 1.308997
    velocity: 1.832596
    acceleration: 3.15
  joint_type: revolute
  passive: false
- default_effort_units: newton_meter
  default_units: radian
  joint_identifier: joint_3
  joint_limits:
    effort: 0.0
    lower: -2.116665
    upper: 1.570796
    velocity: 1.658063
    acceleration: 3.15
  joint_type: revolute
  passive: false
- default_effort_units: newton_meter
  default_units: radian
  joint_identifier: joint_4
  joint_limits:
    effort: 0.0
    lower: -6.283185
    upper: 6.283185
    velocity: 2.094395
    acceleration: 3.15
  joint_type: revolute
  passive: false
- default_effort_units: newton_meter
  default_units: radian
  joint_identifier: joint_5
  joint_limits:
    effort: 0.0
    lower: -2.181662
    upper: 2.181662
    velocity: 2.094395
    acceleration: 3.15
  joint_type: revolute
  passive: false
- default_effort_units: newton_meter
  default_units: radian
  joint_identifier: joint_6
  joint_limits:
    effort: 0.0
    lower: -6.283185
    upper: 6.283185
    velocity: 3.490658
    acceleration: 3.15
  joint_type: revolute
  passive: false
