device_info:
  device:
    name: fanuc_robot
  manufacturer:
    name: FANUC
    uuid: ee260e78-d731-415a-84ca-4b02c487410c
  model:
    name: FANUC_m710ic_45m
    uuid: 9ad3c0ee-ec5e-4057-a297-d340e1484f01
  user_description: Rethink Robotics Sawyer Robot
  serial_number: 123456789
  device_classes:
    - class_identifier:
        name: robot
        uuid: 39b513e7-21b9-4b49-8654-7537473030eb
      subclasses: 
        - serial
        - serial_six_axis        
  implemented_types:
    - com.robotraconteur.robotics.robot.Robot
robot_type: serial
robot_capabilities:
- jog_command
- trajectory_command
- position_command
chains:
- kin_chain_identifier: robot_arm
  H:
  - x: 0.0
    y: 0.0
    z: 1.0
  - x: 0.0
    y: 1.0
    z: 0.0
  - x: 0.0
    y: -1.0
    z: 0.0
  - x: -1.0
    y: 0.0
    z: 0.0
  - x: 0.0
    y: -1.0
    z: 0.0
  - x: -1.0
    y: 0.0
    z: 0.0
  P:
  - x: 0.0
    y: 0.0
    z: 0.565
  - x: 0.15
    y: 0.0
    z: 0.0
  - x: 0.0
    y: 0.0
    z: 1.15
  - x: 0.0
    y: 0.0
    z: 0.17
  - x: 1.295
    y: 0.0
    z: 0.0
  - x: 0.175
    y: 0.0
    z: 0.0
  - x: 0.0
    y: 0.0
    z: 0.0
  flange_identifier: tool0
  flange_pose:
    orientation:
      w: 4.329780281177467e-17
      x: 0.7071067811865476
      y: -4.3297802811774664e-17
      z: 0.7071067811865475
    position:
      x: 0.0
      y: 0.0
      z: 0.0
  joint_numbers:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  link_identifiers:
  - base_link
  - link_1
  - link_2
  - link_3
  - link_4
  - link_5
  - link_6
joint_info:
- default_effort_units: newton_meter
  default_units: radian
  joint_identifier: joint_1
  joint_limits:
    effort: 0.0
    lower: -3.141592653589793
    upper: 3.141592653589793
    velocity: 3.141592653589793
    acceleration: 3.15
  joint_type: revolute
  passive: false
- default_effort_units: newton_meter
  default_units: radian
  joint_identifier: joint_2
  joint_limits:
    effort: 0.0
    lower: -1.5707963267948966
    upper: 2.356194490192345
    velocity: 3.141592653589793
    acceleration: 3.15
  joint_type: revolute
  passive: false
- default_effort_units: newton_meter
  default_units: radian
  joint_identifier: joint_3
  joint_limits:
    effort: 0.0
    lower: -2.792526803190927
    upper: 4.886921905584122
    velocity: 3.141592653589793
    acceleration: 3.15
  joint_type: revolute
  passive: false
- default_effort_units: newton_meter
  default_units: radian
  joint_identifier: joint_4
  joint_limits:
    effort: 0.0
    lower: -6.981317007977318
    upper: 6.981317007977318
    velocity: 4.363323129985824
    acceleration: 3.15
  joint_type: revolute
  passive: false
- default_effort_units: newton_meter
  default_units: radian
  joint_identifier: joint_5
  joint_limits:
    effort: 0.0
    lower: -2.181661564992912
    upper: 2.181661564992912
    velocity: 4.363323129985824
    acceleration: 3.15
  joint_type: revolute
  passive: false
- default_effort_units: newton_meter
  default_units: radian
  joint_identifier: joint_6
  joint_limits:
    effort: 0.0
    lower: -6.981317007977318
    upper: 6.981317007977318
    velocity: 6.283185307179586
    acceleration: 3.15
  joint_type: revolute
  passive: false

