kinematic_plugins:
  search_libraries:
    - tesseract_kinematics_opw_factories
  fwd_kin_plugins:
    ABB_6640_180_255:
      default: KDLFwdKinChain
      plugins:
        KDLFwdKinChain:
          class: KDLFwdKinChainFactory
          config:
            base_link: ABB_6640_180_255_base_link
            tip_link: ABB_6640_180_255_tool0
    ABB_1200_5_90:
      default: KDLFwdKinChain
      plugins:
        KDLFwdKinChain:
          class: KDLFwdKinChainFactory
          config:
            base_link: ABB_1200_5_90_base_link
            tip_link: ABB_1200_5_90_tool0


  inv_kin_plugins:
    ABB_6640_180_255:
      default: KDLInvKinChainLMA
      plugins:
        KDLInvKinChainLMA:
          class: KDLInvKinChainLMAFactory
          config:
            base_link: ABB_6640_180_255_base_link
            tip_link: ABB_6640_180_255_tool0
        KDLInvKinChainNR:
          class: KDLInvKinChainNRFactory
          config:
            base_link: ABB_6640_180_255_base_link
            tip_link: ABB_6640_180_255_tool0

    ABB_1200_5_90:
      default: KDLInvKinChainLMA
      plugins:
        KDLInvKinChainLMA:
          class: KDLInvKinChainLMAFactory
          config:
            base_link: ABB_1200_5_90_base_link
            tip_link: ABB_1200_5_90_tool0
        KDLInvKinChainNR:
          class: KDLInvKinChainNRFactory
          config:
            base_link: ABB_1200_5_90_base_link
            tip_link: ABB_1200_5_90_tool0
